In [3]:
import pandas as pd
import numpy as np

# 1. How likely is it that you roll doubles when rolling two dice?

In [6]:
#outcomes = [1, 2, 3, 4, 5, 6]
#
#n_simulations = 1_000_000
#n_trials = 2
#
#rolls = np.random.choice(outcomes, size=(n_simulations, n_trials))

In [14]:
first_roll = np.random.choice([1, 2, 3, 4, 5, 6], size=1_000_000)
second_roll = np.random.choice([1, 2, 3, 4, 5, 6], size=1_000_000)

In [21]:
id_of_rolls = first_roll / second_roll == 1

#(id(outcomes[0]) == id(outcomes[1])).mean()
id_of_rolls

array([False,  True, False, ..., False, False, False])

In [22]:
id_of_rolls.mean()

0.166674

# 2. If you flip 8 coins, what is the probability of getting exactly 3 heads? 

In [25]:
outcomes = [1, 0]

n_simulations = 1_000_000
n_trials = 8

flips = np.random.choice(outcomes, size=(n_simulations, n_trials))

In [26]:
num_of_heads = flips.sum(axis=1)
(num_of_heads == 3).mean()

0.219087

## 2a. What is the probability of getting more than 3 heads?

In [27]:
(num_of_heads > 3).mean()

0.636353

# 3. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. 
## Assuming that Codeup randomly selects an alumni to put on a billboard:
- what are the odds that the two billboards I drive past both have data science students on them?

In [176]:
#1=DS, 0=WD
outcomes = [1, 0]

drive_by = np.random.choice(outcomes, size=(10_000, 2), p=[0.25, 0.75])
drive_by

array([[0, 1],
       [1, 0],
       [1, 0],
       ...,
       [0, 0],
       [0, 1],
       [0, 0]])

In [177]:
num_of_ds = drive_by.sum(axis=1)

In [178]:
(num_of_ds == 2).mean()

0.0624

# 4. Codeup students buy, on average, 3 poptart packages (+- 1.5) a day from the snack vending machine. 
## If on monday the machine is restocked with 17 poptart packages: 
- how likely is it that I will be able to buy some poptarts on Friday afternoon?

In [185]:
poptart_left = np.random.normal(3, 1.5, size=(1_000_000, 5))
poptart_left

array([[ 4.8999515 ,  4.53320425,  3.98688021,  3.00611441,  3.28541107],
       [-0.38833458,  0.40179285,  1.19544275,  3.03551767,  5.88872867],
       [ 4.25592128,  5.16432527,  4.71142888,  1.85579536,  1.97277883],
       ...,
       [ 3.78412293,  5.91936094,  2.43538261,  2.25622927,  3.96572623],
       [ 4.60553521,  3.2427174 ,  3.08101299,  5.69798514,  4.11771941],
       [ 2.78987651,  1.76462504,  5.83643011,  0.06177244,  5.02321394]])

In [188]:
#num_left = 17 - poptart_left.sum(axis=1)
poptarts_left = (poptart_left.sum(axis=1))

In [189]:
#(num_left >= 1).mean()
(poptarts_left < 17).mean()

0.724445

# 5. Compare Heights
- Men have an average height of 178 cm and standard deviation of 8cm.
- Women have a mean of 170, sd = 6cm.
## If a man and woman are chosen at random, P(woman taller than man)?

In [46]:
males = np.random.normal(178, 8, size=(1_000_000, 2))
females = np.random.normal(170, 6, size=(1_000_000, 2))

In [42]:
(females > males).mean()

0.211692

# 6. When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. 
# What are the odds that after having 50 students download anaconda, no one has an installation issue? 

In [108]:
#anaconda_50 = np.random.binomial(50, .004, 1_000_000)

#1=success, 0= failure
outcomes = [1, 0]

anaconda_50 = np.random.choice(outcomes, size=(100_000, 50), p=[0.996, 0.004])
anaconda_50

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]])

In [109]:
#(anaconda_50 == 0).mean()
anaconda_50 = anaconda_50.sum(axis=1)
(anaconda_50 == 50).mean()

0.81704

In [57]:
#drill_prob = (np.random.binomial(9, 0.1, 20000))
#drill_prob

array([1, 2, 0, ..., 0, 2, 0])

In [65]:
#(drill_prob == 0).mean()

0.3909

## 6a. 100 students?

In [110]:
#anaconda_100 = np.random.binomial(100, .004, 1_000_000)

#1=success, 0= failure
outcomes = [1, 0]

anaconda_100 = np.random.choice(outcomes, size=(100_000, 100), p=[0.996, 0.004])
anaconda_100

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]])

In [111]:
#(anaconda_100 == 0).mean()

anaconda_100 = anaconda_100.sum(axis=1)
(anaconda_100 == 100).mean()

0.66915

## 6b. What is the probability that we observe an installation issue within the first 150 students that download anaconda?

In [77]:
#anaconda_150 = np.random.binomial(150, .996, 1_000_000)

In [78]:
#(anaconda_150 == 0).mean()

0.0

In [122]:
#1=failure, 0= success
outcomes = [1, 0]

anaconda_150 = np.random.choice(outcomes, size=(100_000, 150), p=[0.004, 0.996])
anaconda_150

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [123]:
anaconda_150 = anaconda_150.sum(axis=1)
(anaconda_150 > 0).mean()

0.44838

## 6c. How likely is it that 450 students all download anaconda without an issue?

In [79]:
#anaconda_450 = np.random.binomial(450, .004, 1_000_000)

In [80]:
#(anaconda_450 == 0).mean()

0.165212

In [124]:
#1=success, 0= failure
outcomes = [1, 0]

anaconda_450 = np.random.choice(outcomes, size=(100_000, 450), p=[0.996, 0.004])
anaconda_450

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]])

In [125]:
anaconda_450 = anaconda_450.sum(axis=1)
(anaconda_450 == 450).mean()

0.16538

# 7. There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How *unlikely* is this?

In [85]:
#foodtruck = np.random.binomial(3, .3, 1_000_000)

In [86]:
#(foodtruck == 0).mean()

0.342106

In [126]:
#1=no food truck, 0= food truck
outcomes = [1, 0]

no_food_truck = np.random.choice(outcomes, size=(100_000, 3), p=[0.3, 0.7])
no_food_truck

array([[1, 0, 1],
       [1, 1, 0],
       [1, 0, 1],
       ...,
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [127]:
no_food_truck = no_food_truck.sum(axis=1)
(no_food_truck == 3).mean()

0.02745

## 7a. How likely is it that a food truck will show up sometime this week?

In [91]:
#foodt_wk = np.random.binomial(1, .3, 7)

In [92]:
#(foodt_wk == 0).mean()

0.8571428571428571

In [95]:
#fdt_wk = np.random.binomial(7, .7, 7)

In [96]:
#(fdt_wk).mean()

4.142857142857143

In [97]:
#from scipy.stats import binom

In [100]:
#binom.pmf(k = 1, n = 7, p = .7)

0.0035721000000000025

In [190]:
#1=food truck, 0= no food truck
outcomes = [1, 0]

food_truck = np.random.choice(outcomes, size=(100_000, 2), p=[0.7, 0.3])
food_truck

array([[1, 1],
       [0, 1],
       [0, 0],
       ...,
       [1, 1],
       [1, 1],
       [1, 1]])

In [191]:
food_truck = food_truck.sum(axis=1)
(food_truck >= 1).mean()

0.9098

# 8. If 23 people are in the same room, what are the odds that two of them share a birthday? 

In [133]:
d = np.power((364/365), ((23 * 22)/2))
d

0.4995228459634194

In [192]:
#1=same birthday, 0= different birthday
outcomes = range(0, 365)

same_bday = np.random.choice(outcomes, size=(1_000_000, 23))
same_bday #ea reps a day on the calendar

array([[ 39,  82,  23, ...,  68, 313,  12],
       [350, 258, 177, ..., 255,  10, 239],
       [ 75, 322, 224, ..., 342, 246, 215],
       ...,
       [206, 287,  71, ..., 219,  42, 200],
       [245,  28, 203, ..., 112,  88,  51],
       [363, 153, 112, ..., 142, 226, 111]])

In [196]:
same_bday23 = [len(np.unique(same_bday[n])) for n in range(0, 1_000_000-1) if len(np.unique(same_bday[n]) < 23)]

In [175]:
days = [*range(1, 366, 1)]
days

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185

In [164]:
same_bday1 = np.random.choice(days, size=(100_000, 23))
same_bday1

array([[303, 106,  12, ..., 333, 325,   7],
       [291,  69,  68, ..., 336, 283,  41],
       [151, 320, 267, ...,  52,  43,  83],
       ...,
       [334,  98, 316, ..., 274, 236, 141],
       [184, 202,  29, ..., 360, 184, 147],
       [ 25, 192, 183, ..., 334, 184, 179]])

In [166]:
df = pd.DataFrame(same_bday1)
df

0    1    2    3    4    5    6    7    8    9   ...   13   14   15  \
0      303  106   12  291  294  361  222  112  306  306  ...  205  284  326   
1      291   69   68    9  231  265   19  202   63   61  ...  336   58  221   
2      151  320  267  136  240   55  298   87  267  319  ...  176  132  356   
3        3  303  159  149  358  186   40  228  108  255  ...   55   81    5   
4       85  300   14  105  267  110  318  164  195  134  ...   57  217    5   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
99995  148  204  111  214  351  234  224  212   32   96  ...  217   23  203   
99996   57  172  236  289  322   78  169  236   57  242  ...  193  271   35   
99997  334   98  316   94   44  143  195  340   65  112  ...   20    4  162   
99998  184  202   29   55  252  232  288  109  174  354  ...  219    8   80   
99999   25  192  183   97  144   59  291  340  353  116  ...  309  124   73   

        16   17   18   19   20   21   22  
0      199  304  209  311  333  325    7  
1       90   81  354  108  336  283   41  
2       14  326  105  323   52   43   83  
3       21   20  175  349  280  184  271  
4       89  171  246  309  132    5  282  
...    ...  ...  ...  ...  ...  ...  ...  
99995  164   47  227   75  238  184  335  
99996   90    7   29  317  225  273   63  
99997  282  321  356   27  274  236  141  
99998  111   34    8  117  360  184  147  
99999   38    2  314  217  334  184  179  

[100000 rows x 23 columns]

In [167]:
unibdays = pd.Series(df.nunique(axis=1)) 
unibdays

0        22
1        22
2        22
3        23
4        22
         ..
99995    23
99996    21
99997    23
99998    21
99999    23
Length: 100000, dtype: int64

In [168]:
(unibdays < 23).mean()

0.5098

## 8a. What if it's 20 people? 

In [ ]:
days = [*range(1, 366, 1)]

In [169]:
same_bday20 = np.random.choice(days, size=(100_000, 20))
same_bday20

array([[247, 201,   4, ..., 363, 361, 360],
       [316, 342, 175, ..., 165,  71, 347],
       [216,  46,  79, ..., 256,  27,  13],
       ...,
       [361, 271, 108, ..., 200, 240, 143],
       [130, 157, 181, ..., 351,  18,  22],
       [ 85, 199, 166, ..., 134,   9, 315]])

In [170]:
df2 = pd.DataFrame(same_bday20)
df2

0    1    2    3    4    5    6    7    8    9    10   11   12   13  \
0      247  201    4  145  115  107  148  173  122  141  337  199   11   28   
1      316  342  175  240   93   43   58   78  206  348   97  214  198  339   
2      216   46   79   73  308  175  130  239  214   60  148   76  206  304   
3      300  246  345  305  320  264  248   93  146  303  134   73  299  260   
4       43  334  225   26  225  284  248  278  177  147  354  313  263  331   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
99995  220   65  259  320  232   54  289  104   12   77  106  287  344  155   
99996  294  163   68  342   59  217   43  340  324   39  344  115   73  280   
99997  361  271  108  120  292  188  213  267   18  321  167  133    2   23   
99998  130  157  181  164  285  327  203  348  108  139   42  283   90   50   
99999   85  199  166  255  127  230   92  268  246  312   13   37  342  275   

        14   15   16   17   18   19  
0      353  289   88  363  361  360  
1       61  213  279  165   71  347  
2      138  224  126  256   27   13  
3      195  313  237   50   70  122  
4      152  318   84  139   74  339  
...    ...  ...  ...  ...  ...  ...  
99995  224   64   73  310  282  200  
99996  214  185   19   83  204  275  
99997  218  188   79  200  240  143  
99998   74  289  160  351   18   22  
99999   34   96   33  134    9  315  

[100000 rows x 20 columns]

In [173]:
unibdays20 = pd.Series(df2.nunique(axis=1)) 
unibdays20

0        20
1        20
2        20
3        20
4        19
         ..
99995    20
99996    20
99997    19
99998    20
99999    20
Length: 100000, dtype: int64

In [174]:
(unibdays20 < 20).mean()

0.41075

## 8b. 40?

In [ ]:
days = [*range(1, 366, 1)]

In [ ]:
same_bday40 = np.random.choice(days, size=(100_000, 40))
same_bday40

In [ ]:
df3 = pd.DataFrame(same_bday40)
df3

In [ ]:
unibdays40 = pd.Series(df3.nunique(axis=1)) 
unibdays40

In [ ]:
(unibdays40 < 40).mean()