In [1]:
from pydataset import data

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from scipy import stats

# Mage Duel
Let's use what we've learned to play a mage duel!

Imagine your wizard has **6d4 health points** and you have spells that do **6d4 damage**. 
- "6d4" means rolling six 4-sided dice and summing the result.

Your opposing mage has **4d6 health** points and **spells that do 4d6**. 
- "4d6" means rolling four six-sided dice and summing the result.

### Exercises
Simulate mage duels to answer who is the more powerful mage?

Before running simulations, do you have a hypothesis of which mage will win? Do you have a hunch? Write it down. This is your first exercise.

In [ ]:
# I have a feeling the 6d4 has the advantage with more rolls, although, they both have the same max roll.

Simulate 10 mage duels. Is there a clear winner? Run that 10 duel simulation again. Was the answer similar?


In [18]:
outcomes6d4 = [1, 2, 3, 4]
outcomes4d6 = [1, 2, 3, 4, 5, 6]

simulations = 10
trial6d4 = 6
trial4d6 = 4

duels6d4 = np.random.choice(outcomes6d4, size=(simulations, trial6d4))
duels4d6 = np.random.choice(outcomes4d6, size=(simulations, trial4d6))

In [19]:
((duels6d4.sum(axis=1)) > (duels4d6.sum(axis=1))).mean()

0.5

In [20]:
((duels6d4.sum(axis=1)) < (duels4d6.sum(axis=1))).mean()

0.4

In [21]:
duels6d4

array([[3, 3, 2, 2, 2, 3],
       [1, 1, 4, 3, 1, 3],
       [3, 3, 1, 4, 1, 3],
       [2, 1, 2, 2, 3, 2],
       [4, 4, 4, 1, 2, 3],
       [3, 1, 2, 2, 4, 2],
       [4, 4, 3, 1, 3, 3],
       [2, 1, 4, 1, 3, 4],
       [1, 2, 4, 4, 3, 3],
       [4, 3, 1, 2, 3, 3]])

In [22]:
duels4d6

array([[3, 5, 4, 1],
       [3, 2, 6, 2],
       [5, 1, 5, 5],
       [6, 6, 3, 4],
       [4, 6, 6, 4],
       [6, 4, 6, 2],
       [4, 3, 1, 6],
       [2, 1, 6, 4],
       [6, 3, 2, 4],
       [1, 2, 3, 1]])

In [23]:
duels6d4.sum(axis=1)

array([15, 13, 15, 12, 18, 14, 18, 15, 17, 16])

In [24]:
duels4d6.sum(axis=1)

array([13, 13, 16, 19, 20, 18, 14, 13, 15,  7])

Do the results change much at 100 duels?

In [25]:
duels6d4 = np.random.choice(outcomes6d4, size=(100, trial6d4))
duels4d6 = np.random.choice(outcomes4d6, size=(100, trial4d6))

In [26]:
((duels6d4.sum(axis=1)) > (duels4d6.sum(axis=1))).mean()

0.6

In [27]:
((duels6d4.sum(axis=1)) < (duels4d6.sum(axis=1))).mean()

0.31

Now, simulate 10,000 mage duels. Is there a clear winner?

In [28]:
duels6d4 = np.random.choice(outcomes6d4, size=(10_000, trial6d4))
duels4d6 = np.random.choice(outcomes4d6, size=(10_000, trial4d6))

In [29]:
((duels6d4.sum(axis=1)) > (duels4d6.sum(axis=1))).mean()

0.5433

In [30]:
((duels6d4.sum(axis=1)) < (duels4d6.sum(axis=1))).mean()

0.3683

# Simulating Chuck a Luck
## "Pay a Buck and Chuck-a-Luck"


In [40]:
outcomes = [1, 2, 3, 4, 5, 6]
outcomes

[1, 2, 3, 4, 5, 6]

In [36]:
simulations = 1_000_000
trials = 3

rolls = np.random.choice(outcomes, size = (simulations, trials))
rolls

array([[1, 6, 5],
       [5, 2, 1],
       [3, 3, 1],
       ...,
       [1, 4, 5],
       [1, 2, 4],
       [1, 3, 1]])

In [35]:
#rolls = np.random.choice(outcomes, simulations * trials).reshape(simulations, trials)
#rolls

array([[3, 1, 5],
       [2, 5, 6],
       [3, 3, 6],
       ...,
       [2, 5, 3],
       [6, 5, 2],
       [6, 4, 1]])

In [37]:
#roll1 = np.random.choice(outcomes, size = (simulations, trials))
#roll2 = np.random.choice(outcomes, size = (simulations, trials))
#roll3 = np.random.choice(outcomes, size = (simulations, trials))

In [41]:
df = pd.DataFrame(rolls)
df

0  1  2
0       1  6  5
1       5  2  1
2       3  3  1
3       3  1  5
4       5  6  2
...    .. .. ..
999995  3  2  4
999996  5  4  3
999997  1  4  5
999998  1  2  4
999999  1  3  1

[1000000 rows x 3 columns]

In [42]:
num = 3

In [ ]:
def game (x, num):
    

In [43]:
df[0]

0         1
1         5
2         3
3         3
4         5
         ..
999995    3
999996    5
999997    1
999998    1
999999    1
Name: 0, Length: 1000000, dtype: int64