In [3]:
import pandas as pd
import numpy as np

# 1. How likely is it that you roll doubles when rolling two dice?

In [6]:
#outcomes = [1, 2, 3, 4, 5, 6]
#
#n_simulations = 1_000_000
#n_trials = 2
#
#rolls = np.random.choice(outcomes, size=(n_simulations, n_trials))

In [14]:
first_roll = np.random.choice([1, 2, 3, 4, 5, 6], size=1_000_000)
second_roll = np.random.choice([1, 2, 3, 4, 5, 6], size=1_000_000)

In [21]:
id_of_rolls = first_roll / second_roll == 1

#(id(outcomes[0]) == id(outcomes[1])).mean()
id_of_rolls

array([False,  True, False, ..., False, False, False])

In [22]:
id_of_rolls.mean()

0.166674

# 2. If you flip 8 coins, what is the probability of getting exactly 3 heads? 

In [25]:
outcomes = [1, 0]

n_simulations = 1_000_000
n_trials = 8

flips = np.random.choice(outcomes, size=(n_simulations, n_trials))

In [26]:
num_of_heads = flips.sum(axis=1)
(num_of_heads == 3).mean()

0.219087

## 2a. What is the probability of getting more than 3 heads?

In [27]:
(num_of_heads > 3).mean()

0.636353

# 3. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. 
## Assuming that Codeup randomly selects an alumni to put on a billboard:
- what are the odds that the two billboards I drive past both have data science students on them?

In [28]:
#1=DS, 0=WD
outcomes = [1, 0]

drive_by = np.random.choice(outcomes, size=(10_000, 2), p=[0.3333333, 0.6666667])
drive_by

array([[0, 1],
       [1, 1],
       [0, 0],
       ...,
       [0, 1],
       [0, 0],
       [0, 1]])

In [29]:
num_of_ds = drive_by.sum(axis=1)

In [31]:
(num_of_ds == 2).mean()

0.1104

# 4. Codeup students buy, on average, 3 poptart packages (+- 1.5) a day from the snack vending machine. 
## If on monday the machine is restocked with 17 poptart packages: 
- how likely is it that I will be able to buy some poptarts on Friday afternoon?

In [32]:
poptart_left = np.random.normal(3, 1.5, size=(1_000_000, 5))
poptart_left

array([[ 1.8638982 ,  2.46496878,  0.91575083,  1.81752459,  3.02355415],
       [ 3.02866627, -1.03505918,  0.84349642,  3.85013142,  2.54901919],
       [ 3.78949908,  1.14807568,  3.85827768,  4.6265024 ,  2.43255029],
       ...,
       [ 3.73855981,  5.0542322 ,  6.16036901,  6.88081177,  3.74129141],
       [ 3.55751588,  0.42397538,  3.98015569,  4.40199119,  3.25446962],
       [ 2.85874337,  3.1426298 ,  4.31808167,  2.71065251,  3.25322196]])

In [35]:
num_left = 17 - poptart_left.sum(axis=1)

In [36]:
(num_left >= 1).mean()

0.61645

# 5. Compare Heights
- Men have an average height of 178 cm and standard deviation of 8cm.
- Women have a mean of 170, sd = 6cm.
## If a man and woman are chosen at random, P(woman taller than man)?

In [46]:
males = np.random.normal(178, 8, size=(1_000_000, 2))
females = np.random.normal(170, 6, size=(1_000_000, 2))

In [42]:
(females > males).mean()

0.211692

# 6. When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. 
# What are the odds that after having 50 students download anaconda, no one has an installation issue? 

In [74]:

anaconda_50 = np.random.binomial(50, .004, 1_000_000)
anaconda_50

array([0, 0, 0, ..., 0, 0, 1])

In [75]:
(anaconda_50 == 0).mean()

0.818404

In [57]:
drill_prob = (np.random.binomial(9, 0.1, 20000))
drill_prob

array([1, 2, 0, ..., 0, 2, 0])

In [65]:
(drill_prob == 0).mean()

0.3909

## 6a. 100 students?

In [71]:
anaconda_100 = np.random.binomial(100, .004, 1_000_000)

In [72]:
(anaconda_100 == 0).mean()

0.670106

## 6b. What is the probability that we observe an installation issue within the first 150 students that download anaconda?

In [77]:
anaconda_150 = np.random.binomial(150, .996, 1_000_000)

In [78]:
(anaconda_150 == 0).mean()

0.0

## 6c. How likely is it that 450 students all download anaconda without an issue?

In [79]:
anaconda_450 = np.random.binomial(450, .004, 1_000_000)

In [80]:
(anaconda_450 == 0).mean()

0.165212

# 7. There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How *unlikely* is this?

In [85]:
foodtruck = np.random.binomial(3, .3, 1_000_000)

In [86]:
(foodtruck == 0).mean()

0.342106

## 7a. How likely is it that a food truck will show up sometime this week?

In [91]:
foodt_wk = np.random.binomial(1, .3, 7)

In [92]:
(foodt_wk == 0).mean()

0.8571428571428571

In [95]:
fdt_wk = np.random.binomial(7, .7, 7)

In [96]:
(fdt_wk).mean()

4.142857142857143

In [97]:
from scipy.stats import binom

In [100]:
binom.pmf(k = 1, n = 7, p = .7)

0.0035721000000000025

# 8. If 23 people are in the same room, what are the odds that two of them share a birthday? 

## 8a. What if it's 20 people? 

## 8b. 40?